### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Bryce-VE** [mrcrowley42/Project5#15]
django logging or dump into file?

**Comment by mnewbery** [comment]
1 Import the logging module then abstract it away - create a new module that does the following:
Read log level from config file - debug, info, warn, critical. If the level is set to warn it will ignore debug and info for example
Output to one log file per day for all modules - the date will appear at the end of the file name
at the end of the day the log file will be closed and a new one created
Check for and log the disk space available on the volume at the start of the day
There will be a function for each level but these will be abstracted away so that one function is used 

log_thing(data, DEBUG)
log_thing(data2, INFO)

where the caps words are global python constants - enums or whatever. Your library will define these values.

2 Bryce will show the team how to create a celery task that creates a new log and does health checks at the start of each day

**Comment by mnewbery** [comment]
Rejected. Add code to check for the existence of the log folder and if it doesn't create the folder. If the log folder doesn't exist the first time a log file is created, Bryce demonstrated that the attempt to log throws an error.

**Comment by mnewbery** [comment]
Did you write the code to check to see if the logging folder already exists and if it doesn't, create the folder for the first time?

**Comment by mnewbery** [comment]
Reviewed ok
